// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfbzCu6Xzp0M8CxZEYbGep5QMYSNiwufE',
    appId: '1:18186091548:web:3e61df97d6355d0d4073d9',
    messagingSenderId: '18186091548',
    projectId: 'vegi-groceries-app',
    authDomain: 'vegi-groceries-app.firebaseapp.com',
    storageBucket: 'vegi-groceries-app.appspot.com',
    measurementId: 'G-6LRMYQXWFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASFvuV8mo0O6jcDSxCGcquVJB3nqLwhUg',
    appId: '1:18186091548:android:188ffa91095be0c14073d9',
    messagingSenderId: '18186091548',
    projectId: 'vegi-groceries-app',
    storageBucket: 'vegi-groceries-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFQyXHuQogpeCtfAl3HrZuJpHymXtooQE',
    appId: '1:18186091548:ios:edbb59e3dcee226f4073d9',
    messagingSenderId: '18186091548',
    projectId: 'vegi-groceries-app',
    storageBucket: 'vegi-groceries-app.appspot.com',
    androidClientId: '18186091548-dj8077p98760kql91bja42es3a8psq20.apps.googleusercontent.com',
    iosClientId: '18186091548-cb8mn7o4bhk8i9igndeqvriaig9laorm.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFQyXHuQogpeCtfAl3HrZuJpHymXtooQE',
    appId: '1:18186091548:ios:edbb59e3dcee226f4073d9',
    messagingSenderId: '18186091548',
    projectId: 'vegi-groceries-app',
    storageBucket: 'vegi-groceries-app.appspot.com',
    androidClientId: '18186091548-dj8077p98760kql91bja42es3a8psq20.apps.googleusercontent.com',
    iosClientId: '18186091548-cb8mn7o4bhk8i9igndeqvriaig9laorm.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );
}
